version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "@patternfly/*"
        dependency-type: "direct"
      - dependency-name: "@cypress/*"
        dependency-type: "direct"
      - dependency-name: "cypress*"
        dependency-type: "direct"
