coverage:
  status:
    project:
      default:
        target: 30%
      unitests:
        target: 20%
        flags:
          - unitests
      e2etests:
        target: 40%
        flags:
          - e2etests

flags:
  unitests:
    carryforward: false
  e2etests:
    carryforward: false
