coverage:
  status:
    project:
      unitests:
        target: 10%
        flags:
          - unitests
      e2etests:
        target: 10%
        flags:
          - e2etests

flags:
  unitests:
    carryforward: false
  e2etests:
    carryforward: false
