apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: sso
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/part-of: tackle
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: keycloak-realm
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:12.0.4
          env:
            - name: KEYCLOAK_USER
              value: "admin"
            - name: KEYCLOAK_PASSWORD
              value: "admin"
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
            - name: KEYCLOAK_IMPORT
              value: /etc/config/konveyor-realm.json
            - name: DB_VENDOR
              value: postgres
            - name: DB_ADDR
              value: keycloak-db
            - name: DB_DATABASE
              value: keycloak_db
            - name: DB_USER
              value: keycloak_username
            - name: DB_PASSWORD
              value: keycloak_password
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
          readinessProbe:
            httpGet:
              path: /auth/realms/master
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /auth/realms/master
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          resources: {}
