apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
  labels:
    app.kubernetes.io/component: rest
    app.kubernetes.io/name: tackle-controls
    app.kubernetes.io/part-of: tackle
  name: tackle-controls
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tackle-controls
      app.kubernetes.io/part-of: tackle
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
        prometheus.io/path: /q/metrics
      labels:
        app.kubernetes.io/component: rest
        app.kubernetes.io/name: tackle-controls
        app.kubernetes.io/part-of: tackle
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: QUARKUS_DATASOURCE_USERNAME
              value: controls_username
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: controls_password
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: jdbc:postgresql://controls-db:5432/controls_db
            - name: QUARKUS_OIDC_AUTH_SERVER_URL
              value: http://keycloak:8080/auth/realms/konveyor
            - name: QUARKUS_OIDC_CLIENT_ID
              value: controls-api
            - name: QUARKUS_OIDC_CREDENTIALS_SECRET
              value: secret
          image: quay.io/konveyor/tackle-controls:latest-native
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /controls/q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: tackle-controls
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /controls/q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          resources: {}