name: PR build container images comment

on:
  pull_request_target:
    types: [opened]

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thanks for your contribution! \n Every commit will generate a new build in https://github.com/${{github.event.pull_request.head.repo.full_name}}/actions/workflows/pr-build-container-images.yml and once the build finishes you should be able to use the container image `docker.pkg.github.com/${{github.event.pull_request.head.repo.full_name}}/tackle-ui` \n To see the full set of container images generated visit https://github.com/${{github.event.pull_request.head.repo.full_name}}/packages'
            })
          github-token: ${{ secrets.GITHUB_TOKEN }}
